# Generated by Django 5.0.4 on 2024-04-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_alter_articles_tag_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles_tag',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', through='articles.Articles_scope', to='articles.articles_tag'),
        ),
    ]
