# Generated by Django 5.0.4 on 2024-04-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_tag_articles_scope_delete_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles_scope',
            name='is_main',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
