# Generated by Django 5.0.4 on 2024-04-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_articles_tag_articles_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='articles_tag',
            name='articles',
            field=models.ManyToManyField(related_name='articles_tag', through='articles.Articles_scope', to='articles.article'),
        ),
    ]
