# Generated by Django 5.0.4 on 2024-04-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_scope_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_tag',
            name='articles',
            field=models.ManyToManyField(related_name='articles_tag', through='articles.Articles_scope', to='articles.article'),
        ),
    ]
