# Generated by Django 5.0.4 on 2024-04-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_options_alter_articles_tag_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_tag',
            name='articles',
            field=models.ManyToManyField(related_name='articles', through='articles.Articles_scope', to='articles.article'),
        ),
    ]
